services:
  - type: web
    name: vladimir-photographer
    env: node
    plan: free
    buildCommand: npm run deploy
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
      - key: CLOUDINARY_URL
        value: cloudinary://373123171552225:9pn1t_2t9tsBGf6P05K-gsRlFYk@dzn3i9vlh
      - key: MONGODB_URI
        value: mongodb+srv://tecnicoyopal2020_db_user:2B3L6BsA3ncWkn5z@cluster0.3hcmdpf.mongodb.net/vladimir_portfolio?retryWrites=true&w=majority&appName=Cluster0
      - key: AUTH_SECRET
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
