services:
  - type: web
    name: vladimir-photographer
    env: node
    plan: free
    buildCommand: npm run deploy
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000
      - key: CLOUDINARY_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
